---

- name: Install golang
  include: golang.yml

- include_vars: golang.yml

- name: Create /var/run/netns dir
  file: path=/var/run/netns state=directory

- name: Download cni repo
  git:
  args:
    repo: "https://github.com/containernetworking/cni.git"
    dest: "{{ go_gopath }}/src/github.com/containernetworking/cni"
    force: yes

- name: Build cni plugins
  shell: . {{ go_profile_entry }}; ./build
  args:
    chdir: "{{ go_gopath }}/src/github.com/containernetworking/cni"

- name: Download cni-opencontrail-plugin repo
  git:
  args:
    repo: "https://github.com/codilime/cni-opencontrail-plugin.git"
    dest: "{{ go_gopath }}/src/github.com/codilime/cni-opencontrail-plugin"
    force: yes
    version: "{{ cni_opencontrail_plugin_version }}"

- name: Build cni-opencontrail-plugin
  shell: . {{ go_profile_entry }}; go build "{{ item }}"
  args:
    chdir: "{{ go_gopath }}/src/github.com/codilime/cni-opencontrail-plugin"
  with_items:
    - "plugins/main/cni_opencontrail_plugin.go"
    - "plugins/ipam/cni_opencontrail_ipam.go"

- name: Create cni dirs
  file:
  args:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{mesos_cni_config_dir}}"
    - "{{mesos_cni_plugins_dir}}"
  tags:
    - cni-configs

- name: Install plugins
  shell: mv "{{ item }}" "{{ mesos_cni_plugins_dir }}"
  with_items:
    - "{{ go_gopath }}/src/github.com/containernetworking/cni/bin/bridge"
    - "{{ go_gopath }}/src/github.com/codilime/cni-opencontrail-plugin/cni_opencontrail_plugin"
    - "{{ go_gopath }}/src/github.com/codilime/cni-opencontrail-plugin/cni_opencontrail_ipam"

- name: Install contrail_cli
  shell: mv "{{ item }}" "/"
  with_items:
    - "{{ go_gopath }}/src/github.com/codilime/cni-opencontrail-plugin/contrail_cli.py"

- name: Copy cni configs
  template:
  args:
    src: "{{ item }}.j2"
    dest: "{{ mesos_cni_config_dir }}/{{ item }}"
  with_items:
    - cni-opencontrail-plugin.conf
    - cni-bridge-plugin.conf
  tags:
    - cni-configs

- name: Restart mesos-slave
  service: name=mesos-slave state=restarted
  tags:
    - cni-configs
